// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVt6Mr-9pPpUSpcNKwtHkBXXKrGkHOviM',
    appId: '1:197669555412:web:bf370b1806cc4806d4ff41',
    messagingSenderId: '197669555412',
    projectId: 'miniprojet-95ad5',
    authDomain: 'miniprojet-95ad5.firebaseapp.com',
    databaseURL: 'https://miniprojet-95ad5-default-rtdb.firebaseio.com',
    storageBucket: 'miniprojet-95ad5.appspot.com',
    measurementId: 'G-5YBJQ8HQG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEnUruT8ggcj4CX8FLAFYEqsWcNuvVf7k',
    appId: '1:197669555412:android:da3ac7bab5596727d4ff41',
    messagingSenderId: '197669555412',
    projectId: 'miniprojet-95ad5',
    databaseURL: 'https://miniprojet-95ad5-default-rtdb.firebaseio.com',
    storageBucket: 'miniprojet-95ad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuIVdrbevs7kZ8rsdk6k9qWDek4EpGraA',
    appId: '1:197669555412:ios:d8875a78c579e780d4ff41',
    messagingSenderId: '197669555412',
    projectId: 'miniprojet-95ad5',
    databaseURL: 'https://miniprojet-95ad5-default-rtdb.firebaseio.com',
    storageBucket: 'miniprojet-95ad5.appspot.com',
    iosClientId: '197669555412-2u0611e3nrtd1mi88bjnqhodod1mmoe2.apps.googleusercontent.com',
    iosBundleId: 'no',
  );
}
